version: "3.4"
services:
  ardupilot:
    network_mode: "host"
    image: janchk/ardupilot:latest
    build:
      context: ..
      dockerfile: docker/ardupilot.dockerfile
    container_name: ardupilot
    # entrypoint: /ardupilot/Tools/autotest/sim_vehicle.py -v ArduCopter  -f gazebo-iris --no-mavproxy
    # entrypoint: /ardupilot/Tools/autotest/sim_vehicle.py -v ArduCopter  -f gazebo-iris --console --map -C --daemon
    entrypoint: /ardupilot/Tools/autotest/sim_vehicle.py -v ArduCopter -f gazebo-iris --console -C --daemon
    environment:
      # - "ROS_MASTER_URI=http://ros-master:11311"
      - "NO_AT_BRIDGE=1"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
      - "XAUTHORITYS"
      - "DISPLAY"

    user: 0:0 #adapt as needed!
    volumes: 
      # share your x11 socket and permissions to the container
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

  # gzweb:
  #   network_mode: "host"
  #   image: janchk/gzweb:latest
  #   container_name: gzweb
  #   user: 0:0
  #   environment:
  #     - "NVM_DIR=/root/.nvm"
  #   # entrypoint:  /bin/bash -c /root/.nvm/nvm.sh && npm

  gz_iq:
    network_mode: "host"
    build:
      context: ..
      dockerfile: docker/gz_iqsim.dockerfile
    image: janchk/gz_iq
    runtime: nvidia
    environment:
      # - "ROS_MASTER_URI=http://ros-master:11311"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
      - "XAUTHORITYS"
      - "DISPLAY"
    #share your user to the container in order to access your x11
    user: 0:0 
    volumes: 
      # share your x11 socket and permissions to the container
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    entrypoint: bash /home/scripts/gz_iqsim/start_gz.sh
    # stdin_open: true 
    # tty: true
    # entrypoint: bash
  apm_iq:
    network_mode: "host"
    build:
      context: ..
      dockerfile: docker/gz_iqsim.dockerfile
    image: janchk/gz_iq
    user: 0:0 
    entrypoint: bash /home/scripts/gz_iqsim/start_apm.sh

  rviz:
    network_mode: "host"
    build: 
      context: ..
      dockerfile: docker/gz_iqsim.dockerfile
    image: janchk/gz_iq
    runtime: nvidia
    environment:
      - "QT_X11_NO_MITSHM=1"
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
      - "XAUTHORITYS"
      - "DISPLAY"
    user: 0:0 
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    # entrypoint: bash -c "source /opt/ros/noetic/setup.bash && rviz"
    entrypoint: bash -c "source /opt/ros/noetic/setup.bash && rosrun rqt_tf_tree rqt_tf_tree & \
               source /opt/ros/noetic/setup.bash && rviz"
  external:
    network_mode: "host"
    container_name: uav_external
    build:
      context: ..
      dockerfile: docker/gz_iqsim.dockerfile
    image: janchk/gz_iq
    runtime: nvidia
    environment:
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
      - "XAUTHORITYS"
      - "DISPLAY"
    user: 0:0 
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./:/opt/host
    stdin_open: true 
    tty: true
    entrypoint: bash
